spring:
  application:
    name: server
  datasource:
    url: jdbc:postgresql://localhost:5432/gamestart
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true